kind = "web"
previewPath = "/"
title = "Mercado Livre - Figurinhas Copa 2026"
version = "1.0.0"
id = "artifacts/mercadolivre-mobile"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18251

[services.development]
run = "pnpm --filter @workspace/mercadolivre-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mercadolivre-mobile", "run", "build" ]
publicDir = "artifacts/mercadolivre-mobile/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18251"
BASE_PATH = "/"
